yarnPath: .yarn/releases/yarn-3.3.0.cjs

nodeLinker: node-modules
npmRegistryServer: 'http://npm.dev.wixpress.com/'

unsafeHttpWhitelist:
  - npm.dev.wixpress.com

enableGlobalCache: false # optional, instructs yarn not to keep a local cache in your repo
